# upgrade Ubuntu distro.

- name: upgrade Ubuntu distro 
  tags: upgrade
  apt: upgrade=dist
  when: ansible_distribution == "Ubuntu"

  # --- IDE tasks --- #
- name: install vscode as snap
  tags: vscode
  snap:  
    name: code
    classic: yes
  when: ansible_distribution == "Ubuntu"

- name: install neovim
  tags: neovim
  apt:
    name: neovim
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: copy neovim config directory
  tags: neovim-config
  copy:
    src: nvim
    dest: /home/{{remote_user}}/.config/nvim
    owner: "{{remote_user}}"
    group: "{{remote_user}}"
    mode: '0777'

# -------------------------------------------- #


# --- Python tasks --- #
- name: install/upgrading Python + virtual environment package
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: make Python projects directory
  file:
    path: /home/{{remote_user}}/python_projects
    state: directory
    owner: "{{remote_user}}"
    group: "{{remote_user}}"
    mode: '0777'

# - name: installing pip packages 
#   pip:
#     name:
#       - hashcrack
# -------------------------------------------- #



# --- Go tasks --- #
# TODO:
# - setup correct directory structure (TBD)
# - create/copy across a ~/.profile file that includes GOROOT and GOPATH (TBD)

- name: install go 
  apt:
    name:
      - golang-go
    state: latest 
  when: ansible_distribution == "Ubuntu"


- name: make Go projects directory
  file:
    path: /home/{{remote_user}}/go_projects
    state: directory
    owner: "{{remote_user}}"
    group: "{{remote_user}}"
    mode: '0777'

# -------------------------------------------- #

